#region GCP

#region Locals
locals {
  pubsub_topic_destination = "pubsub.googleapis.com/projects/${var.infrastructure_project_id}/topics/${google_pubsub_topic.audit_logs_topic.name}"

  # Folder-level log entry parts for the ORGANIZATION include filter.
  # Spliced into the filter only when included_project_ids is also set — in that case the
  # resource.labels.project_id filter would otherwise silently block folder-level log entries
  # (which carry no project_id). No-op for ALL and EXCLUDE modes, where folder-level
  # logs already flow through without any explicit filter clause.
  folder_log_parts = var.integration_type == "ORGANIZATION" ? [for f in var.folder_log_sources : "logName:\"folders/${f}/logs/\""] : []

  # Project filtering applies to ORGANIZATION and FOLDER types.
  # PROJECT sinks are already scoped to the specific project.
  # For ORGANIZATION + INCLUDE: folder_log_parts are ORed in so folder-level
  # audit events are not blocked by the project_id filter.
  project_filter = !contains(["ORGANIZATION", "FOLDER"], var.integration_type) ? "" : (
    length(var.included_project_ids) > 0
    ? (length(local.folder_log_parts) > 0
      ? " AND (resource.labels.project_id=(${join(" OR ", [for p in var.included_project_ids : "\"${p}\""])}) OR ${join(" OR ", local.folder_log_parts)})"
    : " AND resource.labels.project_id=(${join(" OR ", [for p in var.included_project_ids : "\"${p}\""])})")
    : length(var.excluded_project_ids) > 0
    ? " AND NOT resource.labels.project_id=(${join(" OR ", [for p in var.excluded_project_ids : "\"${p}\""])})"
    : ""
  )

  # Build the list of enabled log type filters, then join with OR.
  # Parentheses are always added when multiple log types are enabled — required because
  # a project filter may be appended, and in GCP logging query language AND has higher
  # precedence than OR, so without parens:
  #   LOG_ID("a") OR LOG_ID("b") AND NOT resource.labels.project_id=(...)
  # would be parsed as:
  #   LOG_ID("a") OR (LOG_ID("b") AND NOT resource.labels.project_id=(...))
  # — which would let the first log type bypass the project filter entirely.
  enabled_log_types = compact([
    var.enable_admin_activity_logs ? "LOG_ID(\"cloudaudit.googleapis.com/activity\")" : null,
    # Also captures Google Workspace login events — they arrive as data_access entries but are matched by serviceName, not log ID.
    var.enable_data_access_logs ? "LOG_ID(\"cloudaudit.googleapis.com/data_access\") OR protoPayload.serviceName=\"login.googleapis.com\"" : null,
    var.enable_system_event_logs ? "LOG_ID(\"cloudaudit.googleapis.com/system_event\")" : null,
    var.enable_policy_denied_logs ? "LOG_ID(\"cloudaudit.googleapis.com/policy\")" : null,
    # SA impersonation events are always captured — high-signal security events, not configurable.
    "protoPayload.methodName:\"GenerateAccessToken\"",
  ])

  log_type_filter = length(local.enabled_log_types) == 1 ? local.enabled_log_types[0] : "(${join(" OR ", local.enabled_log_types)})"

  audit_logs_filter = "${local.log_type_filter}${local.project_filter}"

  # GKE/k8s logs are always excluded — covered by the dedicated GKE integration.
  gke_exclusions = [
    {
      name        = "exclude-gke-k8s"
      description = "Exclude all GKE and Kubernetes audit logs."
      filter      = "resource.type=\"k8s_cluster\" OR resource.type=\"gke_cluster\""
    },
  ]

  # sys-* projects are auto-generated by Google Apps Script — one per Apps Script project.
  sys_project_exclusions = [
    {
      name        = "exclude-sys-projects"
      description = "Exclude auto-generated Apps Script system projects (sys-*)."
      filter      = "logName =~ \"^projects/sys-\""
    },
  ]

  # Merge default exclusions with any user-provided custom exclusions.
  effective_exclusions = concat(local.gke_exclusions, local.sys_project_exclusions, var.log_sink_exclusions)

  project_number = data.google_project.infrastructure_project.number
  # Last 5 digits of the org ID — used in SA account_id, IAM role IDs, and WIF pool ID
  # to help distinguish resources across multiple integrations in the same project.
  # gcp_organization_id is validated as ^[0-9]+$ so no sanitization is needed.
  org_id_truncated = substr(var.gcp_organization_id, max(0, length(var.gcp_organization_id) - 5), 5)
  # SA account_id budget: GCP limit = 30 chars, prefix "audit-logs-runner-" = 18 chars → 12 chars remain.
  # resource_suffix_hyphen = org_id_truncated(5) + "-"(1) + resource_suffix(max 6) = 12 chars max.
  resource_suffix_hyphen = format("%s%s", local.org_id_truncated, var.resource_suffix == "" ? "" : "-${var.resource_suffix}")

  # Applied to user-provided names (log sink, Pub/Sub, Secret Manager) to prevent
  # "already exists" errors when the module is applied multiple times in the same project.
  name_suffix = var.resource_suffix != "" ? "-${var.resource_suffix}" : ""

  common_labels = merge(var.labels, {
    upwind-component = "gcp-audit-logs"
  })

  writer_identities = concat(
    [for s in google_logging_organization_sink.audit_logs_sink : s.writer_identity],
    [for s in google_logging_folder_sink.audit_logs_sink : s.writer_identity],
    [for s in values(google_logging_project_sink.audit_logs_sink) : s.writer_identity],
  )
}
#endregion


#region Org-level Logging Sink
resource "google_logging_organization_sink" "audit_logs_sink" {
  count  = var.integration_type == "ORGANIZATION" ? 1 : 0
  org_id = var.gcp_organization_id

  name             = "${var.log_sink_name}${local.name_suffix}"
  description      = var.log_sink_description
  destination      = local.pubsub_topic_destination
  filter           = local.audit_logs_filter
  include_children = true

  dynamic "exclusions" {
    for_each = local.effective_exclusions
    content {
      name        = exclusions.value.name
      description = exclusions.value.description
      filter      = exclusions.value.filter
    }
  }
}
#endregion

#region Folder-level Logging Sink
resource "google_logging_folder_sink" "audit_logs_sink" {
  count  = var.integration_type == "FOLDER" ? 1 : 0
  folder = "folders/${var.folder_id}"

  name             = "${var.log_sink_name}${local.name_suffix}"
  description      = var.log_sink_description
  destination      = local.pubsub_topic_destination
  filter           = local.audit_logs_filter
  include_children = true

  dynamic "exclusions" {
    for_each = local.effective_exclusions
    content {
      name        = exclusions.value.name
      description = exclusions.value.description
      filter      = exclusions.value.filter
    }
  }
}
#endregion

#region Project-level Logging Sinks
resource "google_logging_project_sink" "audit_logs_sink" {
  for_each = var.integration_type == "PROJECT" ? toset(var.monitored_project_ids) : toset([])
  project  = each.value

  name                   = "${var.log_sink_name}${local.name_suffix}"
  description            = var.log_sink_description
  destination            = local.pubsub_topic_destination
  filter                 = local.audit_logs_filter
  unique_writer_identity = true

  dynamic "exclusions" {
    for_each = local.effective_exclusions
    content {
      name        = exclusions.value.name
      description = exclusions.value.description
      filter      = exclusions.value.filter
    }
  }
}
#endregion

#region Pub/Sub Topic
resource "google_pubsub_topic" "audit_logs_topic" {
  name    = "${var.pubsub_topic_name}${local.name_suffix}"
  project = var.infrastructure_project_id

  message_retention_duration = var.message_retention_duration

  labels = local.common_labels

  depends_on = [google_project_service.required_apis]

  lifecycle {
    precondition {
      condition     = !contains(["ORGANIZATION", "FOLDER"], var.integration_type) || !(length(var.included_project_ids) > 0 && length(var.excluded_project_ids) > 0)
      error_message = "included_project_ids and excluded_project_ids are mutually exclusive for ORGANIZATION and FOLDER integration types — use one or the other, not both."
    }
    precondition {
      condition     = contains(["ORGANIZATION", "FOLDER"], var.integration_type) || (length(var.included_project_ids) == 0 && length(var.excluded_project_ids) == 0)
      error_message = "included_project_ids and excluded_project_ids only apply to ORGANIZATION and FOLDER integration types — remove them or switch integration_type to ORGANIZATION or FOLDER."
    }
    precondition {
      condition     = var.integration_type != "FOLDER" || var.folder_id != ""
      error_message = "folder_id must be set when integration_type is FOLDER."
    }
    precondition {
      condition     = var.integration_type != "PROJECT" || length(var.monitored_project_ids) > 0
      error_message = "monitored_project_ids must be non-empty when integration_type is PROJECT."
    }
    precondition {
      condition     = var.integration_type == "ORGANIZATION" || length(var.folder_log_sources) == 0
      error_message = "folder_log_sources only applies to ORGANIZATION integration type."
    }
    precondition {
      condition     = length(var.folder_log_sources) == 0 || length(var.included_project_ids) > 0
      error_message = "folder_log_sources requires included_project_ids to be set. The logName clause is only injected into the sink filter in the included_project_ids code path — when no include filter is present (ALL or EXCLUDE modes), folder-level log entries already flow through without it."
    }
  }
}
#endregion

#region Pub/Sub Subscription
resource "google_pubsub_subscription" "audit_logs_subscription" {
  name    = "${var.pubsub_subscription_name}${local.name_suffix}"
  project = var.infrastructure_project_id
  topic   = google_pubsub_topic.audit_logs_topic.id

  ack_deadline_seconds       = 60
  message_retention_duration = var.message_retention_duration

  labels = local.common_labels

  expiration_policy {
    ttl = "" # never expire — GCP default (31 days inactivity) would silently delete the subscription
  }

  depends_on = [google_project_service.required_apis]
}
#endregion

#region Data Sources
data "google_project" "infrastructure_project" {
  project_id = var.infrastructure_project_id
}
#endregion

#endregion
